# Generated by Django 5.0.7 on 2024-07-16 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='medicine_names',
            new_name='medicine_name',
        ),
    ]
